### ISSUE TITLE
on android jax should only be used as a last resort because it will mess with the JavaScript that was originally in place once rebuilt,  

### ISSUE THREAD

**Issue by Chromium-24** [OAuth-Apis/apis#101]
it is difficult to change back out of JAX or AJAX JAVA must be written before in the build to help avoid these changes in language. The order is the best way to see this much clearer so you aren't fixing things that cannot be fixed before thefiring of the logfile initial

**Comment by gvanderploeg** [comment]
Please clarify your issue (especially the connection with Apis).

**Comment by Chromium-24** [comment]
The APIs are separate issue but since you asked here, on analytics (GOOGLE), a problem with embedding them exists if a user is required to only have access through the developer guide instead of the analytics site. Hackers can prevent any user from accessing all functions of the APIs especially ones that are not listed underneath any application. I've embedded them before through Github, but some hacker accessing my account returned them back to a more vulnerable state I'm not sure why because he/she is using the web kit along with SeaMonkey and Gecko. It didn't make sense to me when one is freezing the I frames and manipulating the APIs because the action can be carried out without messing with the APIs necessarily, so it's like using them as a fall safe in case the individual is unable to keep up with the opening of more than four tabs or messing with an advanced user that uses the same options every time. That would definitively throw off any hacker using just the WebKit So any ideas on how to filter the chief APIs without worrying about the less important ones so that computer function is still almost normal even with hacker attached? Especially when they have added a string in front of the parent.

**Comment by Chromium-24** [comment]
P.s. I hope that is more clear for the comment you submitted because the issue at hand was referring to AJAX, but another repo covering APIs was also listed. I'm not sure if you had been reading all of the different issues and just didn't realize you commented on the wrong repo on the list. Thanks for any help you may have to offer anyways.

**Comment by gvanderploeg** [comment]
Closing issue, I regard it as spam.
