### ISSUE TITLE
As cnntributor I'd like to submit a pull request

### ISSUE THREAD

**Issue by tziai** [OAuth-Apis/apis#109]
We have implemented a new class that allows to get or delete access tokens of a particular owner. We think that would be useful for others too and would like to create a feature branch and submit a pull request.

**Comment by gvanderploeg** [comment]
Hi,

Normally you'd fork the repository and create a branch in your own repository. Then open a pull request here, referencing your own repo.
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
