### ISSUE TITLE
failed build from fresh checkout

### ISSUE THREAD

**Issue by mkeller-upb** [OAuth-Apis/apis#89]
Hi, I want to give this project a try but failed on compiling it; most likely because mvn is new to me. I checked the provided helps and searched the web but were not able to resolve my issue. Please, I would appreciate any hint or assistance. The [error.stdout.txt](https://github.com/OAuth-Apis/apis/files/130722/error.stdout.txt) is attached. Best regards, Matthias

**Comment by gvanderploeg** [comment]
The ultimate error ("InvalidAlgorithmParameterException: the trustAnchors
parameter must be non-empty") together with the first warning ("JAVA_HOME
env variable is not set") make me suspicious of your local Java/maven setup.
- Make sure you have set JAVA_HOME to the home of your JDK
- Make sure you actually use a JDK and not merely a JRE
- What OS are you using?

Some interesting troubleshooting info can be found here:
http://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty

Hope this helps.

With kind regards,
Geert

**Comment by mkeller-upb** [comment]
Awesome, twice, first for your fast response, second for hinting the stackoverflow, which let me (in minutes) to another [entry](http://stackoverflow.com/questions/4764611/java-security-invalidalgorithmparameterexception-the-trustanchors-parameter-mus) claiming some pem's are wrongly configured in Ubuntu (I'm using Ubuntu 15.10). I updated my pems with "update-ca-certificates -f" the maven build was successful. Thanks, best regards, Matthias

**Comment by gvanderploeg** [comment]
Great to hear it solved your issue.
