### ISSUE TITLE
User consent request for Implicit flow

### ISSUE THREAD

**Issue by Rashmi-Kalkur** [OAuth-Apis/apis#90]
User consent id requested for the first time for every user. Once the token is issued to the client and resource owner , consent is never requested again.
In formUserConsentHandler ,I see that if another token is already present for this resource owner and client, no new consent should be requested. 
Even if all the tokens present for this particular client and resource owner are expired , user consent request has not been sent . 
Is this the expected behavior ?
In the case of implicit grant as refresh tokens aren't issued , isn't it right to ask for user consent once the token expires ?
Correct me if I'm wrong.

**Comment by gvanderploeg** [comment]
This is expected behaviour yes.
In case the specification explicitly tells us how to deal with this
situation then this is a 'bug', otherwise it's a matter of taste and then
we might introduce a customization where you can set a flag in the
configuration to control this behaviour.


On 6 June 2016 at 07:48, Rashmi-Kalkur <notifications@github.com> wrote:

> User consent id requested for the first time for every user. Once the
> token is issued to the client and resource owner , consent is never
> requested again.
> In formUserConsentHandler ,I see that if another token is already present
> for this resource owner and client, no new consent should be requested.
> Even if all the tokens present for this particular client and resource
> owner are expired , user consent request has not been sent .
> Is this the expected behavior ?
> In the case of implicit grant as refresh tokens aren't issued , isn't it
> right to ask for user consent once the token expires ?
> Correct me if I'm wrong.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OAuth-Apis/apis/issues/90>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABG69iGZQ4G_ygnYCUDb0dQftAsyA0Y1ks5qI7TLgaJpZM4IulIN>
> .
>

-- 
 <http://www.finalist.nl>

**Comment by Rashmi-Kalkur** [comment]
Thanks.
